// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLwumXBIAekLvoV2mIJdHkYP68fIEMZjU',
    appId: '1:389819859108:web:36719e7c0c1496dbff6631',
    messagingSenderId: '389819859108',
    projectId: 'gym-pro-2026',
    authDomain: 'gym-pro-2026.firebaseapp.com',
    storageBucket: 'gym-pro-2026.firebasestorage.app',
    measurementId: 'G-58L0CHR96L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyx-Imvq_L6mQ3_5J7mAmgcrss86EeIHs',
    appId: '1:389819859108:android:509491928cb90004ff6631',
    messagingSenderId: '389819859108',
    projectId: 'gym-pro-2026',
    storageBucket: 'gym-pro-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQHx1hwiGb7RXXAfJFsqVKqzKGUTFujeE',
    appId: '1:389819859108:ios:e11998f29e083946ff6631',
    messagingSenderId: '389819859108',
    projectId: 'gym-pro-2026',
    storageBucket: 'gym-pro-2026.firebasestorage.app',
    iosBundleId: 'com.example.gympro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'gym-pro-2026',
    storageBucket: 'gym-pro-2026.appspot.com',
    iosBundleId: 'com.example.gympro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLwumXBIAekLvoV2mIJdHkYP68fIEMZjU',
    appId: '1:389819859108:web:6a435b97a836b19fff6631',
    messagingSenderId: '389819859108',
    projectId: 'gym-pro-2026',
    authDomain: 'gym-pro-2026.firebaseapp.com',
    storageBucket: 'gym-pro-2026.firebasestorage.app',
    measurementId: 'G-8T5L5RWDQP',
  );

}