import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../models/membership_card.dart';
import '../services/membership_card_service.dart';
import 'auth_controller.dart';

class MembershipCardController extends GetxController {
  final MembershipCardService _cardService = MembershipCardService();
  final AuthController _authController = Get.find<AuthController>();

  // Observable lists
  final RxList<MembershipCard> cards = <MembershipCard>[].obs;
  final RxList<MembershipCard> filteredCards = <MembershipCard>[].obs;

  // Loading states
  final RxBool isLoading = false.obs;
  final RxBool isCreating = false.obs;
  final RxBool isUpdating = false.obs;

  // Statistics
  final RxMap<String, dynamic> statistics = <String, dynamic>{}.obs;

  // Form controllers
  final TextEditingController cardNameController = TextEditingController();
  final TextEditingController descriptionController = TextEditingController();
  final TextEditingController priceController = TextEditingController();
  final TextEditingController durationController = TextEditingController();
  final TextEditingController searchController = TextEditingController();

  // Form state
  final Rx<CardType> selectedCardType = CardType.member.obs;
  final Rx<DurationType> selectedDurationType = DurationType.months.obs;
  final Rx<DateTime?> selectedCustomEndDate = Rx<DateTime?>(null);
  final RxBool isActiveFilter = true.obs;

  // Current editing card
  final Rx<MembershipCard?> editingCard = Rx<MembershipCard?>(null);

  // Search and filter
  final RxString searchQuery = ''.obs;
  final Rx<CardType?> typeFilter = Rx<CardType?>(null);

  @override
  void onInit() {
    super.onInit();
    loadAllCards();
    loadStatistics();

    // Set default duration to 1 for initial preview
    durationController.text = '1';

    // Listen to search changes
    searchController.addListener(() {
      searchQuery.value = searchController.text;
      filterCards();
    });
  }

  @override
  void onClose() {
    cardNameController.dispose();
    descriptionController.dispose();
    priceController.dispose();
    durationController.dispose();
    searchController.dispose();
    super.onClose();
  }

  // Load all cards
  Future<void> loadAllCards() async {
    try {
      isLoading.value = true;
      final cardList = await _cardService.getAllCards();
      cards.value = cardList;
      filterCards();
    } catch (e) {
      _showError('Không thể tải danh sách thẻ tập: $e');
    } finally {
      isLoading.value = false;
    }
  }

  // Load statistics
  Future<void> loadStatistics() async {
    try {
      final stats = await _cardService.getCardStatistics();
      statistics.value = stats;
    } catch (e) {
      print('Error loading statistics: $e');
    }
  }

  // Filter cards based on search and filters
  void filterCards() {
    List<MembershipCard> filtered = List.from(cards);

    // Apply search filter
    if (searchQuery.value.isNotEmpty) {
      filtered = filtered
          .where(
            (card) => card.cardName.toLowerCase().contains(
              searchQuery.value.toLowerCase(),
            ),
          )
          .toList();
    }

    // Apply type filter
    if (typeFilter.value != null) {
      filtered = filtered
          .where((card) => card.cardType == typeFilter.value)
          .toList();
    }

    // Apply active filter
    if (isActiveFilter.value) {
      filtered = filtered.where((card) => card.isActive).toList();
    }

    filteredCards.value = filtered;
  }

  // Create new card
  Future<void> createCard() async {
    try {
      if (!_validateForm()) return;

      isCreating.value = true;

      final now = DateTime.now();
      // Note: Không cần tính endDate cho template, sẽ tính khi user mua

      final card = MembershipCard(
        id: '', // Will be generated by Firestore
        cardName: cardNameController.text.trim(),
        description: descriptionController.text.trim(),
        cardType: selectedCardType.value,
        durationType: selectedDurationType.value,
        duration: int.tryParse(durationController.text) ?? 0,
        customEndDate: selectedDurationType.value == DurationType.custom
            ? selectedCustomEndDate.value
            : null,
        price: double.tryParse(priceController.text.replaceAll(',', '')) ?? 0.0,
        // Note: endDate không có trong template, sẽ tính khi user mua
        createdAt: now,
        updatedAt: now,
        createdBy: _authController.user?.uid ?? '',
        isActive: true,
      );

      final validationError = _cardService.validateCard(card);
      if (validationError != null) {
        _showError(validationError);
        return;
      }

      await _cardService.createCard(card);
      await loadAllCards();
      await loadStatistics();
      clearForm();

      Get.snackbar(
        'Thành công',
        'Thẻ tập đã được tạo thành công',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.green,
        colorText: Colors.white,
      );
    } catch (e) {
      _showError('Không thể tạo thẻ tập: $e');
    } finally {
      isCreating.value = false;
    }
  }

  // Update existing card
  Future<void> updateCard() async {
    try {
      if (editingCard.value == null || !_validateForm()) return;

      isUpdating.value = true;

      final now = DateTime.now();
      // Note: Template không cần endDate, chỉ cập nhật thông tin template

      final updatedCard = editingCard.value!.copyWith(
        cardName: cardNameController.text.trim(),
        description: descriptionController.text.trim(),
        cardType: selectedCardType.value,
        durationType: selectedDurationType.value,
        duration: int.tryParse(durationController.text) ?? 0,
        customEndDate: selectedDurationType.value == DurationType.custom
            ? selectedCustomEndDate.value
            : null,
        price: double.tryParse(priceController.text.replaceAll(',', '')) ?? 0.0,
        // Note: endDate không có trong template
        updatedAt: now,
      );

      final validationError = _cardService.validateCard(updatedCard);
      if (validationError != null) {
        _showError(validationError);
        return;
      }

      await _cardService.updateCard(updatedCard);
      await loadAllCards();
      await loadStatistics();
      clearForm();

      Get.snackbar(
        'Thành công',
        'Thẻ tập đã được cập nhật thành công',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.green,
        colorText: Colors.white,
      );
    } catch (e) {
      _showError('Không thể cập nhật thẻ tập: $e');
    } finally {
      isUpdating.value = false;
    }
  }

  // Delete card
  Future<void> deleteCard(MembershipCard card) async {
    try {
      final confirmed = await Get.dialog<bool>(
        AlertDialog(
          title: const Text('Xác nhận xóa'),
          content: Text(
            'Bạn có chắc chắn muốn xóa thẻ tập "${card.cardName}"?',
          ),
          actions: [
            TextButton(
              onPressed: () => Get.back(result: false),
              child: const Text('Hủy'),
            ),
            ElevatedButton(
              onPressed: () => Get.back(result: true),
              style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
              child: const Text('Xóa'),
            ),
          ],
        ),
      );

      if (confirmed == true) {
        await _cardService.deleteCard(card.id);
        await loadAllCards();
        await loadStatistics();

        Get.snackbar(
          'Thành công',
          'Thẻ tập đã được xóa thành công',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green,
          colorText: Colors.white,
        );
      }
    } catch (e) {
      _showError('Không thể xóa thẻ tập: $e');
    }
  }

  // Toggle card status
  Future<void> toggleCardStatus(MembershipCard card) async {
    try {
      await _cardService.toggleCardStatus(card.id, !card.isActive);
      await loadAllCards();
      await loadStatistics();

      Get.snackbar(
        'Thành công',
        card.isActive
            ? 'Thẻ tập đã được vô hiệu hóa'
            : 'Thẻ tập đã được kích hoạt',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.green,
        colorText: Colors.white,
      );
    } catch (e) {
      _showError('Không thể thay đổi trạng thái thẻ tập: $e');
    }
  }

  // Load card for editing
  void loadCardForEdit(MembershipCard card) {
    editingCard.value = card;
    cardNameController.text = card.cardName;
    descriptionController.text = card.description;
    selectedCardType.value = card.cardType;
    selectedDurationType.value = card.durationType;
    durationController.text = card.duration.toString();
    priceController.text = card.price.toStringAsFixed(0);
    selectedCustomEndDate.value = card.customEndDate;
  }

  // Clear form
  void clearForm() {
    editingCard.value = null;
    cardNameController.clear();
    descriptionController.clear();
    priceController.clear();
    durationController.text = '1'; // Set default value for preview
    selectedCardType.value = CardType.member;
    selectedDurationType.value = DurationType.months;
    selectedCustomEndDate.value = null;
  }

  // Set type filter
  void setTypeFilter(CardType? type) {
    typeFilter.value = type;
    filterCards();
  }

  // Toggle active filter
  void toggleActiveFilter() {
    isActiveFilter.value = !isActiveFilter.value;
    filterCards();
  }

  // Validate form
  bool _validateForm() {
    if (cardNameController.text.trim().isEmpty) {
      _showError('Vui lòng nhập tên thẻ tập');
      return false;
    }

    if (cardNameController.text.trim().length < 3) {
      _showError('Tên thẻ tập phải có ít nhất 3 ký tự');
      return false;
    }

    if (descriptionController.text.trim().isEmpty) {
      _showError('Vui lòng nhập mô tả thẻ tập');
      return false;
    }

    if (priceController.text.trim().isEmpty) {
      _showError('Vui lòng nhập giá tiền');
      return false;
    }

    if (priceController.text.trim().length > 9) {
      _showError('Giá tiền không được vượt quá 9 ký tự');
      return false;
    }

    final price = double.tryParse(priceController.text.replaceAll(',', ''));
    if (price == null || price <= 0) {
      _showError('Giá tiền phải là số dương');
      return false;
    }

    if (selectedDurationType.value != DurationType.custom) {
      if (durationController.text.trim().isEmpty) {
        _showError('Vui lòng nhập thời gian sử dụng');
        return false;
      }

      if (durationController.text.trim().length > 5) {
        _showError('Số lượng không được vượt quá 5 ký tự');
        return false;
      }

      final duration = int.tryParse(durationController.text);
      if (duration == null || duration <= 0) {
        _showError('Thời gian sử dụng phải là số nguyên dương');
        return false;
      }
    }

    if (selectedDurationType.value == DurationType.custom &&
        selectedCustomEndDate.value == null) {
      _showError('Vui lòng chọn ngày kết thúc');
      return false;
    }

    return true;
  }

  // Show error message
  void _showError(String message) {
    Get.snackbar(
      'Lỗi',
      message,
      snackPosition: SnackPosition.BOTTOM,
      backgroundColor: Colors.red,
      colorText: Colors.white,
    );
  }

  // Get statistics for display
  int get totalCards => statistics['totalCards'] ?? 0;
  int get activeCards => statistics['activeCards'] ?? 0;
  int get memberCards => statistics['memberCards'] ?? 0;
  int get premiumCards => statistics['premiumCards'] ?? 0;
  int get vipCards => statistics['vipCards'] ?? 0;
  double get totalRevenue => statistics['totalRevenue'] ?? 0.0;
  double get averagePrice => statistics['averagePrice'] ?? 0.0;
}
